### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by jarfa** [peterskipper/pizzabutton#1]
I'm intrigued.

**Comment by peterskipper** [comment]
Hahahaha just found this comment and I was like "Who's opening issues?"  I'm demo-ing how to customize your Jupyter notebook with a serverextension (same style package underlies JupyterLab and nbgrader).  I'm hoping to get it picked up as a talk at JupyterCon in New York this August :)

**Comment by peterskipper** [comment]
The install instructions don't work yet, but they will soon...

**Comment by jarfa** [comment]
Sick, we'll hang.
